# Generated by Django 5.0.1 on 2024-04-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0013_zonguser_is42user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2', to='page.zonguser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1', to='page.zonguser')),
            ],
        ),
    ]
