#!/bin/sh

mysql <<EOF
FLUSH PRIVILEGES;
CREATE DATABASE $WP_DB;
CREATE USER '$WP_DB_USR'@'localhost' IDENTIFIED BY '$WP_DB_PASS';
GRANT ALL PRIVILEGES ON $WP_DB.* TO '$WP_DB_USR'@'localhost';
FLUSH PRIVILEGES;
EOF