services:
  # reverse-proxy server
  proxy:
    container_name: proxy-service
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - proxy
    depends_on:
      - frontend-node
      # - backend-django-chat
      # - backend-django-utenti

  # FrontEnd Node.js
  frontend-node:
    container_name: frontend-node
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - proxy
  
  # BackEnd DJango Chat
  # backend-django-chat:
  #   container_name: backend-django-chat
  #   build:
  #     context: ./backend/socket-chat
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - proxy

  # BackEnd DJango Game1
  backend-django-game1:
    container_name: backend-django-game1
    build:
      context: ./backend/game1
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - proxy

  # PostGresSQL
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    networks:
      - proxy
    # volume:
    #   - postgres_data:/var/lib/postgresql/data

# Networks configuration
networks:
  proxy:
    driver: bridge
