services:
  # reverse-proxy
  proxy:
    container_name: proxy
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    depends_on:
      - frontend-node
      - backend-django-game1
      - backend-django-users
      - backend-django-chat

  # FrontEnd Node.js
  frontend-node:
    container_name: frontend-node
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    volumes:
      - vol_img_users:/app/img/app/img_users

  # BackEnd DJango Users
  backend-django-users:
    container_name: backend-django-users
    restart: always
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - vol_img_users:/app/img_users
    depends_on:
      - postgres

  # BackEnd Chat
  backend-django-chat:
    container_name: backend-django-chat
    restart: always
    build:
      context: ./backend/chat
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres

  # BackEnd DJango Game1
  backend-django-game1:
    container_name: backend-django-game1
    restart: always
    build:
      context: ./backend/game1
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres

  # PostGresSQL
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db_postgres:/var/lib/postgresql/data

  # Redis
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    env_file:
      - .env
    networks:
      - backend

# Networks
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

# Volumes
volumes:
  vol_img_users:
    driver: local
  db_postgres:
    driver: local
