services:
  mariadb:
    build:
      context: MariaDB/
      dockerfile: Dockerfile
    command: sh configure.sh
    container_name: mariadb
    image: mariadb-aanghi:latest
    restart: always
    networks:
      - inception
    volumes:
      - mdb_vol:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: WordPress/
      dockerfile: Dockerfile
    command: sh configure.sh
    container_name: wordpress
    image: wordpress-aanghi:latest
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"

  nginx:
    build:
      context: NGINX/
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx-aanghi:latest
    restart: always
    volumes:
      - wp_vol:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      device: /home/aanghi/data/wp_vol
      o: bind
      type: none
  mdb_vol:
    name: mdb_vol
    driver: local
    driver_opts:
      device: /home/aanghi/data/mdb_vol
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge