# Generated by Django 5.0.1 on 2024-02-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of the match')),
                ('score', models.CharField(default='0:0', max_length=10)),
                ('Tm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pollUsers',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True)),
                ('online', models.BooleanField(default=False)),
                ('Alias', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('block', models.ManyToManyField(blank=True, to='page.pollusers')),
                ('friends', models.ManyToManyField(blank=True, to='page.pollusers')),
                ('match', models.ManyToManyField(blank=True, to='page.match')),
                ('reques', models.ManyToManyField(blank=True, to='page.pollusers')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P1', to='page.pollusers'),
        ),
        migrations.AddField(
            model_name='match',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='page.pollusers'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='page.pollusers'),
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matchs', models.ManyToManyField(blank=True, to='page.match')),
                ('users', models.ManyToManyField(blank=True, related_name='Utournaments', to='page.pollusers')),
            ],
        ),
        migrations.AddField(
            model_name='pollusers',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='Tusers', to='page.tournaments'),
        ),
    ]
