# Generated by Django 5.0.1 on 2024-03-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollusers',
            old_name='reques',
            new_name='request',
        ),
    ]
