# Generated by Django 5.0.1 on 2024-03-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_pollusers_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollusers',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='matchs',
        ),
        migrations.RemoveField(
            model_name='pollusers',
            name='block',
        ),
        migrations.RemoveField(
            model_name='pollusers',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='pollusers',
            name='request',
        ),
        migrations.RemoveField(
            model_name='pollusers',
            name='tournaments',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='users',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='pollUsers',
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
