# Generated by Django 5.0.1 on 2024-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0004_remove_pollusers_match_remove_tournaments_matchs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZongUser',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(blank=True)),
                ('online', models.BooleanField(default=False)),
                ('Alias', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
