# Generated by Django 5.0.1 on 2024-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_zonguser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonguser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
