# Generated by Django 5.0.1 on 2024-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_zonguser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonguser',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zonguser',
            name='Alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='zonguser',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
