# Generated by Django 5.0.1 on 2024-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_zonguser_game_total_zonguser_game_won_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonguser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
