# Generated by Django 5.0.1 on 2024-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_zonguser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonguser',
            name='is42User',
            field=models.BooleanField(null=True),
        ),
    ]
