# Generated by Django 5.0.1 on 2024-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_remove_zonguser_is42user_zonguser_istwofactorenabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonguser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='zonguser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
