# Generated by Django 5.0.1 on 2024-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_remove_zonguser_phone_number_zonguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonguser',
            name='lastCodeSent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonguser',
            name='lastSentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonguser',
            name='twoFactorCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
