# Generated by Django 5.0.1 on 2024-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_remove_zonguser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonguser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='page.zonguser'),
        ),
    ]
