# Generated by Django 5.0.1 on 2024-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_zonguser_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonguser',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='blocked', to='page.zonguser'),
        ),
    ]
