# Generated by Django 5.0.1 on 2024-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_alter_zonguser_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonguser',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='blocked', to='page.zonguser'),
        ),
    ]
