export let text = {
    p1: "Imagine an amazing homepage",
    p2: "In case of difficulty, have some _ _ _ _ (insert your favorite product)<br> and resume the fun",
    p3: "Imagine an amazing games collection",
    p4: "Local Pong: 2 - 4 Players",
    p5: "Imagine a better Form and Register",
    p6: "Name",
    p7: "Confirm Password",
    p8: "Register",
    p9: "Have an account? Log in here",
    p10: "Imagine a better Form and Log In",
    p11: "Log In",
    p12: "Don't have an account? Register here",
    p13: "Imagine a better Form and<br>Enter the code sent to your email",
    p14: "OTP Code",
    p15: "Send",
    p16: "Arrow Up",
    p17: "Number of players: ",
    p18: "Next",
    p19: "Go back",
    p20: "Names cannot be empty",
    p21: "Player names must be different",
    p22: "Press [Space] to start",
    p23: "Customize the game",
    p24: "Mode",
    p25: "Classic",
    p26: "Start",
    p27: "Game duration: ",
    p28: " minutes",
    p29: "Paddle movement speed: ",
    p30: "Imagine a beautiful page: 404 Resource Not Found",
    p31: "Return to the amazing games list",
    p32: "Victory for ",
    p33: "Draw",
    p34: "Arrow Down",
    p35: "Ball movement speed: ",
    p36: "Home",
    p37: "Play",
    p38: "Modules",
    p39: "Email",
    p40: "Password",
    p41: "Profile",
    p42: "Statistics",
    p43: "Logout",
    p44: "Local Pong with AI: 2 - 4 Players",
    p45: "Number of players: ",
    p46: "Invalid credentials",
    p47: "Internal error",
    p48: "Incorrect code",
    p49: "Username or Email already in use",
    p50: "Passwords do not match",
    p51: "Number of players in the tournament: ",
    p52: "Local Pong Tournament: 2 - 4 Players",
	p53: "Tournament in progress...",
	p54: "Next participants:",
	p55: "Round",
	p56: "Winner",
	p57: "Continue tournament",
};