export let text = {
p1: "Imagine an amazing home page",
p2: "If you're struggling, take _ _ _ _ (insert your favorite product)<br> and get back to having fun",
p3: "Imagine an amazing game collection",
p4: "Local Pong: 2 - 4 Players",
p5: "Imagine a better form and Sign Up",
p6: "Name",
p7: "Confirm Password",
p8: "Sign Up",
p9: "Already have an account? Log in here",
p10: "Imagine a better form and Log In",
p11: "Log In",
p12: "Don't have an account? Sign up here",
p13: "Imagine a better form and<br>Enter the code sent to your email",
p14: "OTP Code",
p15: "Submit",
p16: "Arrow Up",
p17: "Number of players: ",
p18: "Next",
p19: "Back",
p20: "Names cannot be empty",
p21: "Player names must be different",
p22: "Press [Space] to start",
p23: "Customize the game",
p24: "Mode",
p25: "Classic",
p26: "Start",
p27: "Game duration: ",
p28: " minutes",
p29: "Paddle movement speed: ",
p30: "Imagine a beautiful page: 404 Resource not found",
p31: "Return to the amazing game list",
p32: "Victory for ",
p33: "Draw",
p34: "Arrow Down",
p35: "Ball movement speed: ",
p36: "Home",
p37: "Play",
p38: "Modules",
p39: "Email",
p40: "Password",
p41: "Profile",
p42: "Stats",
p43: "Log Out",
p44: "Local Pong with AI: 2 - 4 Players",
p45: "Number of players: ",
p46: "Wrong credentials",
p47: "Internal error",
p48: "Incorrect code",
p49: "Name or email already in use",
p50: "Passwords do not match",
p51: "Number of players in the tournament: ",
p52: "Local Tournament Pong: 2 - 4 Players",
p53: "Tournament in progress...",
p54: "Next participants: ",
p55: "Turn",
p56: "Winner",
p57: "Continue tournament",
p58: "Tournament finished",
p59: "Error saving the match in the records",
p60: "Imagine better stats",
p61: "(Stats not improving? Don't worry, it happens to everyone...)",
p62: "Draws: ",
p63: "Wins: ",
p64: "Losses: ",
p65: "Total matches: ",
p66: "Error retrieving data",
p67: "Invalid JWT code",
p68: "No data available",
p69: "Victory",
p70: "Defeat",
p71: "Total tournaments: ",
p72: "All fields are required",
p73: "Profile",
p74: "Edit Profile",
p75: "Profile Image",
p76: "Edit",
p77: "Cancel",
p78: "Profile image must be max 5MB",
p79: "Profile image must be a .png",
p80: "Friend list",
p81: "Request list",
p82: "Friends",
p83: "No friends? Don't imagine them, that's schizophrenia...",
p84: "Female",
p85: "Other",
p86: "Male",
p87: "You have no friends :(",
p88: "No friend requests",
p89: "Add friends",
p90: "No potential friends found",
p91: "Search for your potential friend",
p92: "Error sending request",
p93: "Select your gender: ",
p94: "A lot",
p95: "Really? :\\",
p96: "Error sending message",
p97: "Your friend already sent the request",
p98: "Error retrieving messages",
p99: "Your friend doesn't want to hear from you",
p100: "Invite a friend",
p101: "Where to find me",
p102: "Friend's name",
p103: "Game",
p104: "Invite",
p105: "Come and play: ",
p106: "; at ",
p107: "Go back",
p108: "Friend profile",
p109: "Status",
};