export let text = {
    p1: "Immagina una fighissima home page",
    p2: "In caso di difficolta, farsi di _ _ _ _ (inserire il suo prodotto preferito)<br> e riprendere il divertimento",
    p3: "Immagina una fighissima raccolta giochi",
    p4: "Pong Locale: 2 - 4 Giocatori",
    p5: "Immagina un Form migliore e Registrati",
    p6: "Nome",
    p7: "Converma Password",
    p8: "Registrati",
    p9: "Hai un account? Accedi qui",
    p10: "Immagina un Form migliore e Accedi",
    p11: "Accedi",
    p12: "Non hai un account? Registrati qui",
    p13: "Immagina un Form migliore e<br>Inserisci il codice inviato nella mail",
    p14: "Codice OTP",
    p15: "Invia",
    p16: "Freccia alto",
    p17: "Numero dei giocatori: ",
    p18: "Avanti",
    p19: "Torna indietro",
    p20: "I nomi non possono essere vuoti",
    p21: "I nomi dei giocatori devo essere diversi",
    p22: "Premi [Spazio] per iniziare",
    p23: "Persolalizza il gioco",
    p24: "Modalita",
    p25: "Classico",
    p26: "Inizia",
    p27: "Tempo della partita: ",
    p28: " minuti",
    p29: "Velocita di movimento delle racchete: ",
    p30: "Immagine una bellissima pagina: 404 Risorsa non trovata",
    p31: "Torna al fantastico elenco giochi",
    p32: "Vittoria per ",
    p33: "Pareggio",
    p34: "Freccia basso",
    p35: "Velocita di movimento della palla: ",
    p36: "Home",
    p37: "Gioca",
    p38: "Moduli",
    p39: "Email",
    p40: "Password",
    p41: "Profilo",
    p42: "Statistiche",
    p43: "Esci",
    p44: "Pong Locale con IA: 2 - 4 Giocatori",
    p45: "Numero giocatori: ",
    p46: "Credenziali errate",
    p47: "Errore interno",
    p48: "Codice sbaliato",
    p49: "Nome o Email gia usata",
    p50: "Le password non coincidono",
    p51: "Numero dei giocatori nel torneo: ",
    p52: "Torneo locale Pong: 2 - 4 Giocatori",
    p53: "Torneo in corso...",
    p54: "Prossimi partecipanti: ",
    p55: "Turno",
    p56: "Vincitore",
    p57: "Continua torneo",
    p58: "Torneo concluso",

    p59: "Errore nel salvare la partita nei registri",
    p60: "Immagina delle statistiche migliori",
    p61: "(Tranqui non sei scarso... Ma giochi da troppo poco)",
    p62: "",
    p63: "",
    p64: "",
    p65: "",
    p66: "",
    p67: "",
    p68: "",
    p69: "",

	// p0: "",
    // p1: "",
    // p2: "",
    // p3: "",
    // p4: "",
    // p5: "",
    // p6: "",
    // p7: "",
    // p8: "",
    // p9: "",
};