export let text = {
p1: "Immagina una fantastica home page",
p2: "In caso di difficoltà, prendi _ _ _ _ (inserisci il tuo prodotto preferito)<br> e torna a divertirti",
p3: "Immagina una fantastica raccolta di giochi",
p4: "Pong Locale: 2 - 4 Giocatori",
p5: "Immagina un form migliore e Registrati",
p6: "Nome",
p7: "Conferma Password",
p8: "Registrati",
p9: "Hai già un account? Accedi qui",
p10: "Immagina un form migliore e Accedi",
p11: "Accedi",
p12: "Non hai un account? Registrati qui",
p13: "Immagina un form migliore e<br>Inserisci il codice inviato nella mail",
p14: "Codice OTP",
p15: "Invia",
p16: "Freccia su",
p17: "Numero di giocatori: ",
p18: "Avanti",
p19: "Indietro",
p20: "I nomi non possono essere vuoti",
p21: "I nomi dei giocatori devono essere diversi",
p22: "Premi [Spazio] per iniziare",
p23: "Personalizza il gioco",
p24: "Modalità",
p25: "Classico",
p26: "Inizia",
p27: "Durata della partita: ",
p28: " minuti",
p29: "Velocità di movimento delle racchette: ",
p30: "Immagina una bellissima pagina: 404 Risorsa non trovata",
p31: "Torna al fantastico elenco giochi",
p32: "Vittoria per ",
p33: "Pareggio",
p34: "Freccia giù",
p35: "Velocità di movimento della palla: ",
p36: "Home",
p37: "Gioca",
p38: "Moduli",
p39: "Email",
p40: "Password",
p41: "Profilo",
p42: "Statistiche",
p43: "Esci",
p44: "Pong Locale con IA: 2 - 4 Giocatori",
p45: "Numero di giocatori: ",
p46: "Credenziali errate",
p47: "Errore interno",
p48: "Codice sbagliato",
p49: "Nome o email già utilizzati",
p50: "Le password non coincidono",
p51: "Numero di giocatori nel torneo: ",
p52: "Torneo locale Pong: 2 - 4 Giocatori",
p53: "Torneo in corso...",
p54: "Prossimi partecipanti: ",
p55: "Turno",
p56: "Vincitore",
p57: "Continua torneo",
p58: "Torneo concluso",
p59: "Errore nel salvare la partita nei registri",
p60: "Immagina delle statistiche migliori",
p61: "(Non ti migliorano le statistiche? Tranquillo, capita a tutti...)",
p62: "Pareggi: ",
p63: "Vittorie: ",
p64: "Sconfitte: ",
p65: "Partite totali: ",
p66: "Errore nell'ottenimento dei dati",
p67: "Codice JWT non valido",
p68: "Nessun dato disponibile",
p69: "Vittoria",
p70: "Sconfitta",
p71: "Tornei totali: ",
p72: "Tutti i campi sono obbligatori",
p73: "Profilo",
p74: "Modifica Profilo",
p75: "Immagine profilo",
p76: "Modifica",
p77: "Annulla",
p78: "Immagine profilo di massimo 5 MB",
p79: "L'immagine profilo deve essere un .png",
p80: "Lista amici",
p81: "Lista richieste",
p82: "Amici",
p83: "Se non hai amici, non immaginarli, questo è schizofrenia...",
p84: "Femmina",
p85: "Altro",
p86: "Maschio",
p87: "Non hai amici :(",
p88: "Non hai richieste di amicizia",
p89: "Aggiungi amici",
p90: "Nessun potenziale amico trovato",
p91: "Cerca il tuo potenziale amico",
p92: "Errore nell'invio della richiesta",
p93: "Seleziona il tuo sesso: ",
p94: "Tanto",
p95: "Serio? :\\",
p96: "Errore nell'invio del messaggio",
p97: "Il tuo amico ti ha già inviato la richiesta",
p98: "Errore nel recupero dei messaggi",
p99: "Il tuo amico non vuole sentirti",
p100: "Invita un amico",
p101: "Dove raggiungermi",
p102: "Nome amico",
p103: "Gioco",
p104: "Invita",
p105: "Vieni a giocare: ",
p106: "; al ",
p107: "Torna indietro",
p108: "Profilo amico",
p109: "Stato",
p110: "Email non valida",
p111: "Nome gia in uso",
p112: "Verifia a 2 fattori",
p113: "Nessuna",
p114: "OTP via email",
p115: "Colore gioco",
p116: "",
p117: "",
p118: "",
p119: "",
};