export let text = {
    p1: "Immagina una fighissima home page",
    p2: "In caso di difficolta, farsi di _ _ _ _ (inserire il suo prodotto preferito)<br> e riprendere il divertimento",
    p3: "Immagina una fighissima raccolta giochi",
    p4: "Pong Locale: 2 - 4 Giocatori",
    p5: "Immagina un Form migliore e Registrati",
    p6: "Nome",
    p7: "Converma Password",
    p8: "Registrati",
    p9: "Hai un account? Accedi qui",
    p10: "Immagina un Form migliore e Accedi",
    p11: "Accedi",
    p12: "Non hai un account? Registrati qui",
    p13: "Immagina un Form migliore e<br>Inserisci il codice inviato nella mail",
    p14: "Codice OTP",
    p15: "Invia",
    p16: "Freccia alto",
    p17: "Numero dei giocatori: ",
    p18: "Avanti",
    p19: "Torna indietro",
    p20: "I nomi non possono essere vuoti",
    p21: "I nomi dei giocatori devo essere diversi",
    p22: "Premi [Spazio] per iniziare",
    p23: "Persolalizza il gioco",
    p24: "Modalita",
    p25: "Classico",
    p26: "Inizia",
    p27: "Tempo della partita: ",
    p28: " minuti",
    p29: "Velocita di movimento delle racchete: ",
    p30: "Immagine una bellissima pagina: 404 Risorsa non trovata",
    p31: "Torna al fantastico elenco giochi",
    p32: "Vittoria per ",
    p33: "Pareggio",
    p34: "Freccia basso",
    p35: "Velocita di movimento della palla: ",
    p36: "Home",
    p37: "Gioca",
    p38: "Moduli",
    p39: "Email",
    p40: "Password",
    p41: "Profilo",
    p42: "Statistiche",
    p43: "Esci",
    p44: "Pong Locale con IA: 2 - 4 Giocatori",
    p45: "Numero giocatori: ",
    p46: "Credenziali errate",
    p47: "Errore interno",
    p48: "Codice sbaliato",
    p49: "Nome o Email gia usata",
    p50: "Le password non coincidono",
    p51: "Numero dei giocatori nel torneo: ",
    p52: "Torneo locale Pong: 2 - 4 Giocatori",
    p53: "Torneo in corso...",
    p54: "Prossimi partecipanti: ",
    p55: "Turno",
    p56: "Vincitore",
    p57: "Continua torneo",
    p58: "Torneo concluso",
    p59: "Errore nel salvare la partita nei registri",
    p60: "Immagina delle statistiche migliori",
    p61: "(Non ti si alzano le statistiche? Tranquillo capita a tutti...)",
    p62: "Pareggi: ",
    p63: "Vittorie: ",
    p64: "Sconfitte: ",
    p65: "Totali partite: ",
    p66: "Errore nel ottenimento dei dati",
    p67: "Codice JWT non valido",
    p68: "Nessun dato disponibile",
    p69: "Vittoria",
	p70: "Sconfitta",
    p71: "Totali tornei: ",
    p72: "Tutti i campi sono richiesti",
    p73: "Profilo",
    p74: "Modifica Profilo",
    p75: "Immagine profilo",
    p76: "Modifica",
    p77: "Annulla",
    p78: "Immagine profilo di massimo 5Mb",
    p79: "Immagine profilo deve essere un .png",
	p80: "Lista amici",
    p81: "Lista richieste",
    p82: "Amici",
    p83: "Se non hai amici non immaginarli, questo e schiffotrenia...",
    p84: "Femmina",
    p85: "Altro",
    p86: "Maschio",
    p87: "Non hai amici : (",
    p88: "Non hai richieste di amicizia",
    p89: "Aggiungi amici",
    p90: "Nessun potenziale amico trovato",
    p91: "Cerca il tuo potenziale amico",
    p92: "Errore nel spedire la richiesta",
    p93: "Seleziona il tuo sesso: ",
    p94: "Tanto",
    p95: "Serio? : \\",
    p96: "Errore nel mandare il messaggio",
    p97: "Il tuo amico ti ha gia inviato la richiesta",
    p98: "Errore nel recupero dei messaggi",
    p99: "Il tuo amico non ti vuole sentire",

    // p10: "",
    // p11: "",
    // p12: "",
    // p13: "",
    // p14: "",
    // p15: "",
    // p16: "",
    // p17: "",
    // p18: "",
    // p19: "",
};