export let text = {
    p1: "Imagine na bella casa 'e accoglienza",
    p2: "Si 'a cosa nun va, pigliate nu poco 'e _ _ _ _ (mett' 'o prodotto tuo preferito)<br> e ricummencia 'a divertette",
    p3: "Imagine na bella raccolta 'e giuoche",
    p4: "Pong Locale: 2 - 4 Giucature",
    p5: "Imagine nu meglio modulo pe' registrarte",
    p6: "Nome",
    p7: "Confirmma 'a Passwèrd",
    p8: "Registrate",
    p9: "Tieni già 'nu conto? Trase ccà",
    p10: "Imagine nu meglio modulo pe' trasì",
    p11: "Trase",
    p12: "Nun tieni nu conto? Registrate ccà",
    p13: "Imagine nu meglio modulo<br>e mitt' 'o codice mannato a' mail tua",
    p14: "Codice OTP",
    p15: "Manna",
    p16: "Freccia 'n coppa",
    p17: "Nummero 'e giucature: ",
    p18: "Prossimo",
    p19: "Turna arrete",
    p20: "I nomme nun ponno sta vacante",
    p21: "I nomme d'i giucature adda essere diverso",
    p22: "Strign' [Space] pe' accumencià",
    p23: "Personalizza 'o gioco",
    p24: "Modo",
    p25: "Classico",
    p26: "Accumencia",
    p27: "Durata 'e 'o gioco: ",
    p28: " minuti",
    p29: "Velocità 'e 'o movimento 'e 'a racchetta: ",
    p30: "Imagine na pagina bellissima: 404 Risorsa Nun Trovata",
    p31: "Turna a' lista 'e giuoche belli",
    p32: "Vittoria pe' ",
    p33: "Parità",
    p34: "Freccia 'n bass",
    p35: "Velocità 'e 'o movimento 'e 'a pallina: ",
    p36: "Casa",
    p37: "Gioca",
    p38: "Moduli",
    p39: "Email",
    p40: "Passwèrd",
    p41: "Profilo",
    p42: "Statistiche",
    p43: "Esci",
    p44: "Pong Locale cu l'IA: 2 - 4 Giucature",
    p45: "Nummero 'e giucature: ",
    p46: "Credenziale sbagliate",
    p47: "Errore interno",
    p48: "Codice sbagliato",
    p49: "Nome o Email già utilizzata",
    p50: "E password nun so uguale",
    p51: "Nnummero e' giocature dinto 'o turneo: ",
    p52: "Turneo locale 'e Pong: 2 - 4 Giucature",
	p53: "Torne in corso...",
	p54: "Prossimi partecipanti:",
	p55: "Turno",
	p56: "Vincitore",
	p57: "Continua 'o torneo",
};