export let text = {
p1: "Pienz' a 'na pagina home fighissima",
p2: "Si staje 'n difficoltà, piglia _ _ _ _ (miett' o' prodotto tuo preferito)<br> e ricomincia a divertirti",
p3: "Pienz' a 'na raccolta 'e giochi fantastica",
p4: "Pong Locale: 2 - 4 Giocatori",
p5: "Pienz' a 'nu form meglie e Registrate",
p6: "Nome",
p7: "Conferma Password",
p8: "Registrate",
p9: "Tieni già 'nu account? Trase ccà",
p10: "Pienz' a 'nu form meglie e Trase",
p11: "Trase",
p12: "Nun tieni 'nu account? Registrate ccà",
p13: "Pienz' a 'nu form meglie e<br>Mitt' o codice mannato 'ncoppa a mail",
p14: "Codice OTP",
p15: "Manna",
p16: "Freccia 'ngopp'",
p17: "Nummero 'e giocatori: ",
p18: "Avanza",
p19: "Ritorna",
p20: "I nomme nun ponno essere vacante",
p21: "I nomme 'e giocatori devono essere diverse",
p22: "Sping' [Spazio] pe' accumincia'",
p23: "Personalizza 'o gioco",
p24: "Modalità",
p25: "Classico",
p26: "Accumincia'",
p27: "Durata d' 'a partita: ",
p28: " minute",
p29: "Velocità 'e movimento 'e racchette: ",
p30: "Pienz' a 'na bellissima pagina: 404 Risorsa nun trovata",
p31: "Ritorna 'a fantastica lista 'e giochi",
p32: "Vittoria pe' ",
p33: "Pareggio",
p34: "Freccia abbascio",
p35: "Velocità 'e movimento d' 'a palla: ",
p36: "Home",
p37: "Gioca",
p38: "Moduli",
p39: "Email",
p40: "Password",
p41: "Profilo",
p42: "Statistiche",
p43: "Esci",
p44: "Pong Locale cu IA: 2 - 4 Giocatori",
p45: "Nummero 'e giocatori: ",
p46: "Credenziali sbagliate",
p47: "Errore intern",
p48: "Codice sbagliato",
p49: "Nome o email già utilizzati",
p50: "I password nun combaciano",
p51: "Nummero 'e giocatori int' 'o torneo: ",
p52: "Torneo locale Pong: 2 - 4 Giocatori",
p53: "Torneo 'n corso...",
p54: "Prossimi partecipanti: ",
p55: "Turno",
p56: "Vincitore",
p57: "Continua torneo",
p58: "Torneo finuto",
p59: "Errore 'int' 'a salvata d' 'a partita",
p60: "Pienz' a statistiche meglie",
p61: "(E statistiche nun se muovono? Nun t preoccupa, succede a tutt'...)",
p62: "Pareggi: ",
p63: "Vittorie: ",
p64: "Sconfitte: ",
p65: "Partite totali: ",
p66: "Errore 'int' 'a ottene 'e dati",
p67: "Codice JWT nun valido",
p68: "Nisciun dato disponibile",
p69: "Vittoria",
p70: "Sconfitta",
p71: "Tornei totali: ",
p72: "Tutti i campi so' obbligatori",
p73: "Profilo",
p74: "Cagna Profilo",
p75: "Immagine profilo",
p76: "Cagna",
p77: "Annula",
p78: "Immagine profilo massimo 5 MB",
p79: "Immagine profilo adda essere 'nu .png",
p80: "Lista amici",
p81: "Lista richieste",
p82: "Amici",
p83: "Si nun tieni amici, nun t'immaginà, è schizofrenia...",
p84: "Femmena",
p85: "Overo",
p86: "Maschio",
p87: "Nun tieni amici :(",
p88: "Nun tieni richieste 'e amicizia",
p89: "Aggiungi amici",
p90: "Nisciun amico trovato",
p91: "Truv' o' tuo amico potenziale",
p92: "Errore 'int' 'o mannà 'a richiesta",
p93: "Scegli 'o tuo sess': ",
p94: "Tant'",
p95: "Serio? :\\",
p96: "Errore 'int' 'o mannà 'o messaggio",
p97: "O' tuo amico già t'ha mannato 'a richiesta",
p98: "Errore 'int' 'o recuperà 'e messaggi",
p99: "O' tuo amico nun te vo' sentì",
p100: "Invita 'nu amico",
p101: "Dove me truove",
p102: "Nome d' 'o amico",
p103: "Gioco",
p104: "Invita",
p105: "Vieni a giocà: ",
p106: "; a ",
p107: "Turna 'nnanz",
p108: "Profilo d' 'o amico",
p109: "Stato",
p110: "Sta email nun è bona",
p111: "Nome già in uso",
p112: "Verifica a 2 fatture",
p113: "Nisciuna",
p114: "OTP pe' email",
};