services:
  mariadb:
    build:
      context: MariaDB/
      dockerfile: Dockerfile
    command: sh configure.sh
    container_name: mariadb
    restart: always
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - /home/aanghi/data/db:/var/lib/mysql2
    stdin_open: true
    tty: true
    environment:
      WP_DB_PASS: ${WP_DB_PASS}
      WP_DB_USR: ${WP_DB_USR}
      WP_DB: ${WP_DB}

networks:
  inception:
    driver: bridge