# Generated by Django 5.0.1 on 2024-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(null=True),
        ),
    ]
