services:
  mariadb:
    build:
      context: MariaDB/
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      WP_DB_USR: ${WP_DB_USR}
      WP_DB_PASS: ${WP_DB_PASS}
      WP_DB: ${WP_DB}

  wordpress:
    build:
      context: WordPress/
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DB: ${WP_DB}
      WP_DB_USR:  ${WP_DB_USR}
      WP_DB_PASS:  ${WP_DB_PASS}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}
    ports:
      - "9000:9000"
    volumes:
      - /home/aanghi/data/wp:/var/www/html/wp-content
    depends_on:
      - mariadb

  nginx:
    build:
      context: NGINX/
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
