services:
  mariadb:
    build:
      context: MariaDB/
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    networks:
      - inception
    ports:
      - "3306:3306"
    environment:
      WP_DB_USR: ${WP_DB_USR}
      WP_DB_PASS: ${WP_DB_PASS}
      WP_DB: ${WP_DB}

  nginx:
    build:
      context: NGINX/
      dockerfile: Dockerfile
    command: tail -f /dev/null
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge